# Generated by Django 2.1.2 on 2018-10-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0004_auto_20181025_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
