# Generated by Django 2.1.2 on 2018-10-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0006_expense_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('launch', 'Launch'), ('dinner', 'Dinner')], max_length=20, null=True),
        ),
    ]
