# Generated by Django 2.1.2 on 2018-10-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0007_expense_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
