# Generated by Django 2.1.2 on 2018-10-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0008_auto_20181026_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='timestimp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
