# Generated by Django 2.1.2 on 2018-10-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0009_auto_20181027_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='timestimp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
