# Generated by Django 2.1.2 on 2018-10-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0010_auto_20181027_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
