# Generated by Django 2.1.2 on 2018-10-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0011_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
