# Generated by Django 2.1.2 on 2018-10-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0015_auto_20181027_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('item', models.ManyToManyField(to='messApp.Expense')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='messApp.Member')),
            ],
        ),
    ]
