# Generated by Django 2.1.2 on 2018-11-03 16:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0017_auto_20181027_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('timestimp', models.DateTimeField(default=datetime.datetime(2018, 11, 3, 22, 40, 58, 7963))),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messApp.Member')),
            ],
        ),
    ]
