# Generated by Django 2.1.2 on 2018-11-03 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0018_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 3)),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='timestimp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 22, 44, 33, 516555)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 3)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 3)),
        ),
    ]
