# Generated by Django 2.1.2 on 2018-11-03 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0019_auto_20181103_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='timestimp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 22, 44, 37, 315258)),
        ),
    ]
