# Generated by Django 2.1.2 on 2018-11-04 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0020_auto_20181103_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 4)),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='timestimp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 4, 22, 4, 57, 269611)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 4)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 4)),
        ),
    ]
