# Generated by Django 2.1.2 on 2018-11-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0024_auto_20181105_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='timestimp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
