# Generated by Django 2.1.2 on 2018-11-18 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0028_auto_20181118_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
