# Generated by Django 2.1.2 on 2018-11-29 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0030_auto_20181118_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositAs', to='messApp.Member'),
        ),
    ]
