# Generated by Django 2.1.2 on 2018-11-29 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0031_auto_20181129_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messApp.Member'),
        ),
    ]
