# Generated by Django 2.1.2 on 2018-12-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0035_auto_20181206_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Item Name'),
        ),
    ]
