# Generated by Django 2.1.2 on 2018-12-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0036_auto_20181206_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('launch', 'Launch'), ('dinner', 'Dinner')], max_length=20, null=True),
        ),
    ]
